github:
  client_id: 6bfc99a969d394acfa38
  client_secret: 11d10f0f7e6682dd891167c1163c1e7071fe1929
  redirect_uri: http://localhost:8080/callback

ucloud_ufile:
  ufile:
    public-key: TOKEN_521e4bae-4c2a-4e7e-813d-feeadd4bf034
    private-key: 17c2292a-3c5b-425b-b431-72eccca0ee93
    backet-name: luosong
    region: cn-bj
    suffix: ufileos.com
    expires: 315360000

spring:
  datasource:
    url: jdbc:h2:D:/H2/H2
    username: root
    password: 123456
    driver-class-name: org.h2.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: life.luosong.community.mapper
  mapper-locations: classpath:mapper/*.xml

  spring:
    jpa:
      open-in-view: true

file: community.log
level: ''
logging: ''
max-history: 30
max-size: 100MB
root: info









